# Generated by Django 4.0.5 on 2022-06-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Breath', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chat',
        ),
    ]
