# Generated by Django 4.0.5 on 2022-06-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Breath', '0002_rename_room_message_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='room',
        ),
    ]
